spring.application.name=attendance

spring.mongodb.uri=mongodb+srv://anirudh28032006_db_user:2O3JlG3Av2BjvINU@attendancecluster.ojncp0a.mongodb.net/attendance_db?retryWrites=true&w=majority&appName=AttendanceCluster

logging.level.org.springframework.boot.context.config=DEBUG

app.jwt.secret=${JWT_SECRET:QXR0ZW5kYW5jZVN5c3RlbVNlY3JldEtleUZvclYxLjE=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.faculty.initial-username=${INITIAL_FACULTY_USERNAME:admin}
app.faculty.initial-password=${INITIAL_FACULTY_PASSWORD:admin123}