spring.application.name=attendance

spring.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.boot.context.config=DEBUG

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.faculty.initial-username=${INITIAL_FACULTY_USERNAME:admin}
app.faculty.initial-password=${INITIAL_FACULTY_PASSWORD}